version: '3'
services:
  node-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
  mysql:
    image: mysql
    restart: always
    # ports:
    #   - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql:/data/db
volumes:
  mysql:
  # db:
  #   image: mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=123456
  #     - MYSQL_DATABASE=data_adx
    # env_file:
    #   - ./.env