version: '3'
services:
  node-app:
    build: .
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    expose:
      - 5000
    environment:
      - DBUSER=root
      - DBHOST=root
      - DBDATABASE=data_adx
      - DBPASSWORD=root
      - DBPORT=3306
    command: npm run devStart
  mysqldb:
    image: 'mysql:latest'
    restart: always
    ports:
      - "3307:3306"
    expose:
      - 3307
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=data_adx