version: '3'
services:
  node-app:
    build: .
    ports:
      - "5000:3000"
    volumes:
      - ../:/app
      - /app/node_modules
    environment:
      - PORT=5000
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=data_adx
    # env_file:
    #   - ./.env